package com.mahdi.myapp.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated Dec 8, 2015 2:55:39 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointment generated by hbm2java
 */
@Entity
@Table(name = "appointment", catalog = "myfirstapp")
public class Appointment implements java.io.Serializable {

	private Integer id;
	private UserProfile usersByDoctorId;
	private UserProfile usersByPatientId;
	private Date appointmentDate;
	private int status;

	public Appointment() {
	}

	public Appointment(UserProfile usersByDoctorId, UserProfile usersByPatientId, Date appointmentDate, int status) {
		this.usersByDoctorId = usersByDoctorId;
		this.usersByPatientId = usersByPatientId;
		this.appointmentDate = appointmentDate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "doctor_id", nullable = false)
	public UserProfile getUsersByDoctorId() {
		return this.usersByDoctorId;
	}

	public void setUsersByDoctorId(UserProfile usersByDoctorId) {
		this.usersByDoctorId = usersByDoctorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "patient_id", nullable = false)
	public UserProfile getUsersByPatientId() {
		return this.usersByPatientId;
	}

	public void setUsersByPatientId(UserProfile usersByPatientId) {
		this.usersByPatientId = usersByPatientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appointmentDate", nullable = false, length = 19)
	public Date getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
