package com.mahdi.myapp.model;
// Generated Dec 25, 2015 6:16:27 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bookings generated by hbm2java
 */
@Entity
@Table(name = "bookings")
public class Bookings implements java.io.Serializable {

	private Integer id;
	private BookingStatus bookingStatus;
	private UserProfile usersByDoctorId;
	private UserProfile usersByPatientId;
	private String diseasesDescription;
	private Date datetimeStart;
	private Date datetimeEnd;

	public Bookings() {
	}

	public Bookings(BookingStatus bookingStatus, UserProfile usersByDoctorId, UserProfile usersByPatientId,
			String diseasesDescription, Date datetimeStart, Date datetimeEnd) {
		this.bookingStatus = bookingStatus;
		this.usersByDoctorId = usersByDoctorId;
		this.usersByPatientId = usersByPatientId;
		this.diseasesDescription = diseasesDescription;
		this.datetimeStart = datetimeStart;
		this.datetimeEnd = datetimeEnd;
	}

	public Bookings(Date start, Date end) {
		this.bookingStatus = new BookingStatus("Available for Booking", 1);
		this.datetimeStart = start;
		this.datetimeEnd = end;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public BookingStatus getBookingStatus() {
		return this.bookingStatus;
	}

	public void setBookingStatus(BookingStatus bookingStatus) {
		this.bookingStatus = bookingStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public UserProfile getUsersByDoctorId() {
		return this.usersByDoctorId;
	}

	public void setUsersByDoctorId(UserProfile usersByDoctorId) {
		this.usersByDoctorId = usersByDoctorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public UserProfile getUsersByPatientId() {
		return this.usersByPatientId;
	}

	public void setUsersByPatientId(UserProfile usersByPatientId) {
		this.usersByPatientId = usersByPatientId;
	}

	@Column(name = "diseases_description", nullable = false, length = 65535)
	public String getDiseasesDescription() {
		return this.diseasesDescription;
	}

	public void setDiseasesDescription(String diseasesDescription) {
		this.diseasesDescription = diseasesDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime_start", nullable = false, length = 19)
	public Date getDatetimeStart() {
		return this.datetimeStart;
	}

	public void setDatetimeStart(Date datetimeStart) {
		this.datetimeStart = datetimeStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime_end", nullable = false, length = 19)
	public Date getDatetimeEnd() {
		return this.datetimeEnd;
	}

	public void setDatetimeEnd(Date datetimeEnd) {
		this.datetimeEnd = datetimeEnd;
	}

}
