package com.mahdi.myapp.model;
// Generated Dec 25, 2015 6:16:27 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Specialization generated by hbm2java
 */
@Entity
@Table(name = "specialization")
public class Specialization implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<UserProfile> userses = new HashSet<UserProfile>(0);

	public Specialization() {
	}

	public Specialization(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Specialization(String name, String description, Set<UserProfile> userses) {
		this.name = name;
		this.description = description;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specialization")
	public Set<UserProfile> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UserProfile> userses) {
		this.userses = userses;
	}

}
