package com.mahdi.myapp.model;
// Generated Dec 25, 2015 6:16:27 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users",uniqueConstraints = {
		@UniqueConstraint(columnNames = "username"),
		@UniqueConstraint(columnNames = "email") })
public class UserProfile implements java.io.Serializable {

	private Integer id;
	private Specialization specialization;
	private String fullname;
	private String clinicName;
	private String address;
	private String qualification;
	private Integer rating;
	private Integer age;
	private Float expirence;
	private String email;
	private String contact;
	private String username;
	private String password;
	private String profilePicUrl;
	private Byte enabled;
	private String summary;
	private Set<Bookings> bookingsesForDoctorId = new HashSet<Bookings>(0);
	private List<UserRoles> userRoles = new ArrayList<UserRoles>(0);
	private AppointmentSchedule appointmentSchedule;
	private Set<Bookings> bookingsesForPatientId = new HashSet<Bookings>(0);
	private Set<Bookings> allBooking = new HashSet<Bookings>(0);
	public UserProfile() {
	}

	public UserProfile(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public UserProfile(Specialization specialization, String fullname, String clinicName, String address,
			String qualification, Integer rating, Integer age, Float expirence, String email, String contact,
			String username, String password, String profilePicUrl, Byte enabled, String summary,
			Set<Bookings> bookingsesForDoctorId, List<UserRoles> userRoles, AppointmentSchedule appointmentSchedule,
			Set<Bookings> bookingsesForPatientId) {
		this.specialization = specialization;
		this.fullname = fullname;
		this.clinicName = clinicName;
		this.address = address;
		this.qualification = qualification;
		this.rating = rating;
		this.age = age;
		this.expirence = expirence;
		this.email = email;
		this.contact = contact;
		this.username = username;
		this.password = password;
		this.profilePicUrl = profilePicUrl;
		this.enabled = enabled;
		this.summary = summary;
		this.bookingsesForDoctorId = bookingsesForDoctorId;
		this.userRoles = userRoles;
		this.appointmentSchedule = appointmentSchedule;
		this.bookingsesForPatientId = bookingsesForPatientId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specialization_id")
	public Specialization getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}

	@Column(name = "fullname", length = 50)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "clinic_name", length = 50)
	public String getClinicName() {
		return this.clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	@Column(name = "address", length = 1000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "qualification", length = 50)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "expirence", precision = 12, scale = 0)
	public Float getExpirence() {
		return this.expirence;
	}

	public void setExpirence(Float expirence) {
		this.expirence = expirence;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact", length = 15)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profilePicUrl", length = 50)
	public String getProfilePicUrl() {
		return this.profilePicUrl;
	}

	public void setProfilePicUrl(String profilePicUrl) {
		this.profilePicUrl = profilePicUrl;
	}

	@Column(name = "enabled")
	public Byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	@Column(name = "summary", length = 65535)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByDoctorId")
	public Set<Bookings> getBookingsesForDoctorId() {
		return this.bookingsesForDoctorId;
	}

	public void setBookingsesForDoctorId(Set<Bookings> bookingsesForDoctorId) {
		this.bookingsesForDoctorId = bookingsesForDoctorId;
	}

	@ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinTable(name = "user_role_mapping",  joinColumns = {
			@JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role", nullable = false, updatable = false) })
	public List<UserRoles> getUserRoles() {
		return this.userRoles;
	}
	
	public void setUserRoles(List<UserRoles> userRoles) {
		this.userRoles = userRoles;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userProfile", cascade = CascadeType.ALL)
	public AppointmentSchedule getAppointmentSchedule() {
		return this.appointmentSchedule;
	}

	public void setAppointmentSchedule(AppointmentSchedule appointmentSchedule) {
		this.appointmentSchedule = appointmentSchedule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByPatientId")
	public Set<Bookings> getBookingsesForPatientId() {
		return this.bookingsesForPatientId;
	}

	public void setBookingsesForPatientId(Set<Bookings> bookingsesForPatientId) {
		this.bookingsesForPatientId = bookingsesForPatientId;
	}

	@Transient
	public Set<Bookings> getAllBooking() {
		return allBooking;
	}

	public void setAllBooking(Set<Bookings> allBooking) {
		this.allBooking = allBooking;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((address == null) ? 0 : address.hashCode());
		result = prime * result + ((age == null) ? 0 : age.hashCode());
		result = prime * result + ((allBooking == null) ? 0 : allBooking.hashCode());
		result = prime * result + ((appointmentSchedule == null) ? 0 : appointmentSchedule.hashCode());
		result = prime * result + ((bookingsesForDoctorId == null) ? 0 : bookingsesForDoctorId.hashCode());
		result = prime * result + ((bookingsesForPatientId == null) ? 0 : bookingsesForPatientId.hashCode());
		result = prime * result + ((clinicName == null) ? 0 : clinicName.hashCode());
		result = prime * result + ((contact == null) ? 0 : contact.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((enabled == null) ? 0 : enabled.hashCode());
		result = prime * result + ((expirence == null) ? 0 : expirence.hashCode());
		result = prime * result + ((fullname == null) ? 0 : fullname.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((profilePicUrl == null) ? 0 : profilePicUrl.hashCode());
		result = prime * result + ((qualification == null) ? 0 : qualification.hashCode());
		result = prime * result + ((rating == null) ? 0 : rating.hashCode());
		result = prime * result + ((specialization == null) ? 0 : specialization.hashCode());
		result = prime * result + ((summary == null) ? 0 : summary.hashCode());
		result = prime * result + ((userRoles == null) ? 0 : userRoles.hashCode());
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserProfile other = (UserProfile) obj;
		if (address == null) {
			if (other.address != null)
				return false;
		} else if (!address.equals(other.address))
			return false;
		if (age == null) {
			if (other.age != null)
				return false;
		} else if (!age.equals(other.age))
			return false;
		if (allBooking == null) {
			if (other.allBooking != null)
				return false;
		} else if (!allBooking.equals(other.allBooking))
			return false;
		if (appointmentSchedule == null) {
			if (other.appointmentSchedule != null)
				return false;
		} else if (!appointmentSchedule.equals(other.appointmentSchedule))
			return false;
		if (bookingsesForDoctorId == null) {
			if (other.bookingsesForDoctorId != null)
				return false;
		} else if (!bookingsesForDoctorId.equals(other.bookingsesForDoctorId))
			return false;
		if (bookingsesForPatientId == null) {
			if (other.bookingsesForPatientId != null)
				return false;
		} else if (!bookingsesForPatientId.equals(other.bookingsesForPatientId))
			return false;
		if (clinicName == null) {
			if (other.clinicName != null)
				return false;
		} else if (!clinicName.equals(other.clinicName))
			return false;
		if (contact == null) {
			if (other.contact != null)
				return false;
		} else if (!contact.equals(other.contact))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (enabled == null) {
			if (other.enabled != null)
				return false;
		} else if (!enabled.equals(other.enabled))
			return false;
		if (expirence == null) {
			if (other.expirence != null)
				return false;
		} else if (!expirence.equals(other.expirence))
			return false;
		if (fullname == null) {
			if (other.fullname != null)
				return false;
		} else if (!fullname.equals(other.fullname))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (profilePicUrl == null) {
			if (other.profilePicUrl != null)
				return false;
		} else if (!profilePicUrl.equals(other.profilePicUrl))
			return false;
		if (qualification == null) {
			if (other.qualification != null)
				return false;
		} else if (!qualification.equals(other.qualification))
			return false;
		if (rating == null) {
			if (other.rating != null)
				return false;
		} else if (!rating.equals(other.rating))
			return false;
		if (specialization == null) {
			if (other.specialization != null)
				return false;
		} else if (!specialization.equals(other.specialization))
			return false;
		if (summary == null) {
			if (other.summary != null)
				return false;
		} else if (!summary.equals(other.summary))
			return false;
		if (userRoles == null) {
			if (other.userRoles != null)
				return false;
		} else if (!userRoles.equals(other.userRoles))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}
	
	
}
