package com.mahdi.myapp.model;

// default package
// Generated Dec 8, 2015 11:19:09 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles", catalog = "myfirstapp")
public class UserRole implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String description;
	private Boolean isInternal;
	private byte enabled;
	private Set<UserProfile> userses = new HashSet<UserProfile>(0);

	public UserRole() {
	}

	public UserRole(int id, String code, byte enabled) {
		this.id = id;
		this.code = code;
		this.enabled = enabled;
	}

	public UserRole(int id, String code, String name, String description, Boolean isInternal, byte enabled,
			Set<UserProfile> userses) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.description = description;
		this.isInternal = isInternal;
		this.enabled = enabled;
		this.userses = userses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isInternal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<UserProfile> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UserProfile> userses) {
		this.userses = userses;
	}

}
