package com.mahdi.myapp.model;
// Generated Dec 25, 2015 6:16:27 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles")
public class UserRoles implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private String description;
	private Boolean isInternal;
	private byte enabled;
	private Set<UserProfile> userses = new HashSet<UserProfile>(0);

	public UserRoles() {
	}

	public UserRoles(String code, byte enabled) {
		this.code = code;
		this.enabled = enabled;
	}

	public UserRoles(String code, String name, String description, Boolean isInternal, byte enabled,
			Set<UserProfile> userses) {
		this.code = code;
		this.name = name;
		this.description = description;
		this.isInternal = isInternal;
		this.enabled = enabled;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isInternal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role_mapping", joinColumns = {
			@JoinColumn(name = "role", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<UserProfile> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UserProfile> userses) {
		this.userses = userses;
	}

}
