package com.mahdi.myapp.model;

// default package
// Generated Dec 8, 2015 11:19:09 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "myfirstapp")
public class UserProfile implements java.io.Serializable {

	private Integer id;
	private UserRole userRoles;
	private String fullname;
	private String specialty;
	private Integer age;
	private Float expirence;
	private String email;
	private String contact;
	private String username;
	private String password;
	private String profilePicUrl;
	private int enabled;
	private String summary;
	

	private Set<Appointment> appointmentsForDoctorId = new HashSet<Appointment>(0);
	private Set<Appointment> appointmentsForPatientId = new HashSet<Appointment>(0);

	public UserProfile() {
	}

	public UserProfile(int id, UserRole userRoles, String fullname, String username, String password) {
		this.id = id;
		this.userRoles = userRoles;
		this.fullname = fullname;
		this.username = username;
		this.password = password;
	}

	public UserProfile(int id, UserRole userRoles, String fullname, String specialty, Integer age, Float expirence,
			String email, String contact, String username, String password, String profilePicUrl, Byte enabled, String summary,
			Set<Appointment> appointmentsForDoctorId, Set<Appointment> appointmentsForPatientId) {
		this.id = id;
		this.userRoles = userRoles;
		this.fullname = fullname;
		this.specialty = specialty;
		this.age = age;
		this.expirence = expirence;
		this.email = email;
		this.contact = contact;
		this.username = username;
		this.password = password;
		this.profilePicUrl = profilePicUrl;
		this.enabled = enabled;
		this.summary = summary;
		this.appointmentsForDoctorId = appointmentsForDoctorId;
		this.appointmentsForPatientId = appointmentsForPatientId;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role", nullable = false)
	public UserRole getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(UserRole userRoles) {
		this.userRoles = userRoles;
	}

	@Column(name = "fullname", nullable = true, length = 50)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "specialty", length = 100)
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "expirence", precision = 12, scale = 0)
	public Float getExpirence() {
		return this.expirence;
	}

	public void setExpirence(Float expirence) {
		this.expirence = expirence;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact", length = 15)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profilePicUrl", length = 20)
	public String getProfilePicUrl() {
		return this.profilePicUrl;
	}

	public void setProfilePicUrl(String profilePicUrl) {
		this.profilePicUrl = profilePicUrl;
	}

	@Column(name = "summary", length = 4000)
	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "enabled")
	public int getEnabled() {
		return this.enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByDoctorId")
	public Set<Appointment> getAppointmentsForDoctorId() {
		return this.appointmentsForDoctorId;
	}

	public void setAppointmentsForDoctorId(Set<Appointment> appointmentsForDoctorId) {
		this.appointmentsForDoctorId = appointmentsForDoctorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usersByPatientId")
	public Set<Appointment> getAppointmentsForPatientId() {
		return this.appointmentsForPatientId;
	}

	public void setAppointmentsForPatientId(Set<Appointment> appointmentsForPatientId) {
		this.appointmentsForPatientId = appointmentsForPatientId;
	}	
	
}
