-- MySQL Script generated by MySQL Workbench
-- 12/23/15 15:49:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema getdoc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `getdoc` ;

-- -----------------------------------------------------
-- Schema getdoc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `getdoc` DEFAULT CHARACTER SET latin1 ;
USE `getdoc` ;

-- -----------------------------------------------------
-- Table `getdoc`.`appointment_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`appointment_schedule` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`appointment_schedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doctors_id` INT(11) NOT NULL COMMENT '',
  `working_days` VARCHAR(50) NOT NULL COMMENT '',
  `morning_time_start` TIME NULL DEFAULT NULL COMMENT '',
  `morning_time_end` TIME NULL DEFAULT NULL COMMENT '',
  `morning_tokens` INT(11) NOT NULL COMMENT '',
  `afternoon_time_start` TIME NULL DEFAULT NULL COMMENT '',
  `afternoon_time_end` TIME NULL DEFAULT NULL COMMENT '',
  `afternoon_tokens` INT(11) NOT NULL COMMENT '',
  `evening_time_start` TIME NULL DEFAULT NULL COMMENT '',
  `evening_time_end` TIME NULL DEFAULT NULL COMMENT '',
  `evening_tokens` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`booking_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`booking_status` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`booking_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(25) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(50) NOT NULL COMMENT '',
  `name` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `description` VARCHAR(500) NULL DEFAULT NULL COMMENT '',
  `isInternal` BIT(1) NULL DEFAULT NULL COMMENT '',
  `enabled` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`specialization` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`specialization` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `Description` VARCHAR(1000) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`users` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fullname` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `role` INT(11) NOT NULL COMMENT '',
  `specialization_id` INT(11) NOT NULL DEFAULT NULL COMMENT '',
  `clinic_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(1000) NULL DEFAULT NULL COMMENT '',
  `qualification` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `rating` INT(11) NULL DEFAULT NULL COMMENT '',
  `age` INT(5) NULL DEFAULT NULL COMMENT '',
  `expirence` FLOAT NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `contact` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `profilePicUrl` VARCHAR(50) NULL DEFAULT 'patientProfilePic.jpg' COMMENT '',
  `enabled` TINYINT(4) NULL DEFAULT '1' COMMENT '',
  `summary` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`, `specialization_id`)  COMMENT '',
  INDEX `users_user_roles` (`role` ASC)  COMMENT '',
  INDEX `users_specialization_id_idx` (`specialization_id` ASC)  COMMENT '',
  CONSTRAINT `users_user_roles`
    FOREIGN KEY (`role`)
    REFERENCES `getdoc`.`user_roles` (`id`),
  CONSTRAINT `users_specialization_id`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `getdoc`.`specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`bookings` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`bookings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doctor_id` INT(11) NOT NULL COMMENT '',
  `appointment_schedule_id` INT(11) NOT NULL COMMENT '',
  `patient_id` INT(11) NOT NULL COMMENT '',
  `diseases_description` TEXT NOT NULL COMMENT '',
  `datetime_start` DATETIME NOT NULL COMMENT '',
  `datetime_end` DATETIME NOT NULL COMMENT '',
  `status_id` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `bookings_patient` (`patient_id` ASC)  COMMENT '',
  INDEX `bookings_doctor` (`doctor_id` ASC)  COMMENT '',
  INDEX `bookings_appointment_schedule` (`appointment_schedule_id` ASC)  COMMENT '',
  INDEX `bookings_booking_status_idx` (`status_id` ASC)  COMMENT '',
  CONSTRAINT `bookings_appointment_schedule`
    FOREIGN KEY (`appointment_schedule_id`)
    REFERENCES `getdoc`.`appointment_schedule` (`id`),
  CONSTRAINT `bookings_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `getdoc`.`users` (`id`),
  CONSTRAINT `bookings_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `getdoc`.`users` (`id`),
  CONSTRAINT `bookings_booking_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `getdoc`.`booking_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
