-- MySQL Script generated by MySQL Workbench
-- 12/25/15 17:56:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema getdoc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema getdoc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `getdoc` DEFAULT CHARACTER SET latin1 ;
USE `getdoc` ;

-- -----------------------------------------------------
-- Table `getdoc`.`specialization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`specialization` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`specialization` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `Description` VARCHAR(1000) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`users` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `specialization_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `fullname` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `clinic_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(1000) NULL DEFAULT NULL COMMENT '',
  `qualification` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `rating` INT(11) NULL DEFAULT NULL COMMENT '',
  `age` INT(5) NULL DEFAULT NULL COMMENT '',
  `expirence` FLOAT NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `contact` VARCHAR(15) NULL DEFAULT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `profilePicUrl` VARCHAR(50) NULL DEFAULT 'patientProfilePic.jpg' COMMENT '',
  `enabled` TINYINT(4) NULL DEFAULT '1' COMMENT '',
  `summary` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_users_specialization`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `getdoc`.`specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_users_specialization1_idx` ON `getdoc`.`users` (`specialization_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `getdoc`.`appointment_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`appointment_schedule` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`appointment_schedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `working_days` VARCHAR(50) NOT NULL COMMENT '',
  `start_time` DATETIME NULL DEFAULT NULL COMMENT '',
  `end_time` DATETIME NULL DEFAULT NULL COMMENT '',
  `slot_size` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_appointment_schedule_users1`
    FOREIGN KEY (`id`)
    REFERENCES `getdoc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`bookings` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`bookings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `doctor_id` INT(11) NOT NULL COMMENT '',
  `patient_id` INT(11) NOT NULL COMMENT '',
  `diseases_description` TEXT NOT NULL COMMENT '',
  `datetime_start` DATETIME NOT NULL COMMENT '',
  `datetime_end` DATETIME NOT NULL COMMENT '',
  `status_id` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_bookings_users_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `getdoc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_users_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `getdoc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_bookings_users1_idx` ON `getdoc`.`bookings` (`doctor_id` ASC)  COMMENT '';

CREATE INDEX `fk_bookings_users2_idx` ON `getdoc`.`bookings` (`patient_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `getdoc`.`booking_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`booking_status` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`booking_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(25) NOT NULL COMMENT '',
  `code` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_booking_status_bookings1`
    FOREIGN KEY (`id`)
    REFERENCES `getdoc`.`bookings` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(50) NOT NULL COMMENT '',
  `name` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `description` VARCHAR(500) NULL DEFAULT NULL COMMENT '',
  `isInternal` BIT(1) NULL DEFAULT NULL COMMENT '',
  `enabled` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `getdoc`.`user_role_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `getdoc`.`user_role_mapping` ;

CREATE TABLE IF NOT EXISTS `getdoc`.`user_role_mapping` (
  `user_id` INT(11) NOT NULL COMMENT '',
  `role` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `role`)  COMMENT '',
  CONSTRAINT `fk_user_role_mapping_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `getdoc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_mapping_user_roles`
    FOREIGN KEY (`role`)
    REFERENCES `getdoc`.`user_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_user_role_mapping_user_roles1_idx` ON `getdoc`.`user_role_mapping` (`role` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
